sudo: required
services:
  - docker
before_install:
  - docker build -t kubi89/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run  kubi89/react-test npm test -- --coverage

after_succes:
 -docker build -t kubi89/multi-client ./client
 -docker build -t kubi89/multi-nginx ./nginx
 -docker build -t kubi89/multi-server ./server
 -docker build -t kubi89/multi-worker ./worker