sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t kubi89/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true kubi89/react-test npm test

after_success:
  - docker build -t kubi89/multi-client ./client
  - docker build -t kubi89/multi-nginx ./nginx
  - docker build -t kubi89/multi-server ./server
  - docker build -t kubi89/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push kubi89/multi-client
  - docker push kubi89/multi-nginx
  - docker push kubi89/multi-server
  - docker push kubi89/multi-worker

deploy:
provider: elasticbeanstalk
region: us-east-1
app: docker-multicontainer
env: Docker-multicontainer-env
bucket_name: elasticbeanstalk-us-east-1-399057701824
bucket_path: docker-multicontainer
on:
  branch: master
access_key_id: $AWS_ACCESS_KEY
secret_access_key: "$AWS_SECRET_KEY"